apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    svc: details
  name: details
spec:
  selector:
    matchLabels:
      app: bookinfo
      svc: details
  template:
    metadata:
      labels:
        app: bookinfo
        svc: details
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        name: details
      schedulerName: scheduler-plugins-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    svc: details
  name: details
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
  selector:
    app: bookinfo
    svc: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    svc: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: bookinfo
      svc: mongodb
  template:
    metadata:
      labels:
        app: bookinfo
        svc: mongodb
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-mongodb:1.16.2
        name: mongodb
      schedulerName: scheduler-plugins-scheduler  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    svc: mongodb
  name: mongodb
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: bookinfo
    svc: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    svc: productpage
  name: productpage
spec:
  selector:
    matchLabels:
      app: bookinfo
      svc: productpage
  template:
    metadata:
      labels:
        app: bookinfo
        svc: productpage
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        name: productpage
        securityContext:
          runAsUser: 1000
      schedulerName: scheduler-plugins-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    svc: productpage
  name: productpage
spec:
  ports:
  - name: http
    nodePort: 30000
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    svc: productpage
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    svc: reviews
  name: reviews
spec:
  selector:
    matchLabels:
      app: bookinfo
      svc: reviews
  template:
    metadata:
      labels:
        app: bookinfo
        svc: reviews
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        name: reviews
        securityContext:
          runAsUser: 1000
      schedulerName: scheduler-plugins-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    svc: reviews
  name: reviews
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    svc: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookinfo
    svc: ratings
  name: ratings
spec:
  selector:
    matchLabels:
      app: bookinfo
      svc: ratings
  template:
    metadata:
      labels:
        app: bookinfo
        svc: ratings
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v2:1.16.2
        name: ratings
        env:
        - name: MONGO_DB_URL
          value: mongodb://mongodb:27017/test
        securityContext:
          runAsUser: 1000
      schedulerName: scheduler-plugins-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookinfo
    svc: ratings
  name: ratings
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: bookinfo
    svc: ratings